<?php 
	$page = Page :: getInstance(Page :: $HTML5);
	$page -> addCss('css/reset.css','css/one.css');
	$page -> addScript('js/jquery-1.7.js','js/menu.js');
?>
<div class="line"></div>
<div class="logo"><a href="/index" title=""><div class="click_on_logo"></div></a></div>
  <div class="menu_11">

    <ul id='menu'>
    	
		<li class='news'>
			<a href='/news' title="">События</a>
		</li>
    	<li class='th'>
    		
			<a href='/group' title="">Команда</a>
		</li>
		<li class='new_menu'>
			<a href='/backstage' title="">Backstage</a>
		</li>
		<li class='second'>
			<a href='/before-after' title="">До и после</a>
		</li>
		
		<li class='first'>
			<a href='/portfolio' title="">Портфолио</a>
		</li>
		
		
	</ul>
  </div>  
  <div class="under_menu"></div> 