<?php
  $page -> setTitle('Елена Широва - до и после');
    $page -> addScript('js/jquery-1.6.1.min.js','js/jquery-slider.js','js/before-after.js');

?>
<script type="text/javascript">
$(document).ready(function(){

$("#slider").slider({
	min: 0,
	max: 665,
    slide: function(event, ui){
    	$('div.slider_color').css('width',ui.value);	
		$('.picture_hight_width2').css('width',ui.value);  
				
    } 
});

});

</script>
<?php
		$sql_img="SELECT client, description,photo,photo_small FROM before_after  ORDER BY create_time DESC";
		$db->query($sql_img);
		if($db->getCount()>=2) {		
		print '<div class="float_right_arrow">
	  				<div class="arrows_right">
	  				</div>
	  </div>
	  
	   <div class="float_left_arrow">
	   			<div class="arrows_left">
	  			</div>
		</div>';
		}
?>							
<div class="title_0">
			
	<?php			
		
			foreach ($db->getArray() as $value) {
						$value['description']=preg_replace('/\s+$/m', '<br>', $value['description']);
						$mass[]=array('client' => $value['client'], 'description' => $value['description'], 'photo' => $value['photo'], 'photo_small' => $value['photo_small']);
					}	
			
			print '<div class="customer"><span class="customer_font">Заказчик</span><span class="replace">'.$mass[0]['client'].'</span> </div>
	<div class="text_port">'.$mass[0]['description'].' </div>';		
		//print '<div class="customer"><span class="customer_font">Заказчик</span><span class="replace">'.$mass[0]['client'].'</span> <span style="margin:0 5px 0 0;">|</span><span class="text_port_before_after">'.$mass[0]['description'].' </span></div>';	
				
				print '<div class="clear"></div>
				<div class="preloader"></div>
							<div id="picture_before_after">
								
  	 							<div class="picture_hight_width1"></div>
								<div class="picture_hight_width2"></div>
								
								<div class="sliderCont">
										    
											<div id="slider"></div>
											<div class="slider_color"></div>
											
								</div>
							
										
								
  	 						</div>
  	 			</div>';
			?>
		
	<script type="text/javascript"> 
	
	$.config = {
            obj:<?php echo json_encode($mass);?> ,
            current: <?php echo json_encode($current);?>,
            params:<?php echo json_encode($params);?> 
        };
        
  
   </script>	
