<?php
  $page -> setTitle('Елена Широва - Творческая группа');
    $page -> addScript('js/jquery-1.6.1.min.js','js/group.js','js/arrow.js');
	
?>
<div class="shadow"></div>
<?php
	$current=$controller->getController();
	$params=$controller->paramsArray[0];
	
		print ' <div class="float_right_arrow">
					<div class="arrows_right"></div>
	    		</div>
	   <div class="float_left_arrow">
	   			<div class="arrows_left"></div>
		</div>';
				   		
?>
<div class="title_0">
		<ul id='menu_cont_comand'> 
		<li class='current'>
			<a href="/group" title="">Творческая группа</a><span style="margin:0 10px;">|</span>
			</li>
		<li >
			<a href="/partner" title="">Партнеры</a><span style="margin:0 10px;">|</span>
			</li>
			<li>
			<a href="/model" title="">Модели</a>
			</li>
		</ul>
				
		
		<?php
					
	
		
				$sql_models="SELECT name ,position, photo,photo_small, photo_down,description  FROM team_creative ORDER BY weight ASC";
				$db->query($sql_models);
					foreach ($db->getArray() as $value) {
						$value['description']=preg_replace('/\s+$/m', '<br />', $value['description']);
						$size=getimagesize('img/team_creative/'.$value['photo_small']);
						$mass[]=array('name' => $value['name'], 'position' => $value['position'], 'photo' => $value['photo'], 'photo_small' => $value['photo_small'], 'photo_down' => $value['photo_down'], 'description' => $value['description'],'width'=>$size[0]);	
									}
					

		print '<div class="clear"></div>
				<div class="preloader"></div>
							<div id="one">  </div>
  	 			</div>';
		?>	
		
		
							
	<script type="text/javascript"> 
	
	$.config = {
            obj:<?php echo json_encode($mass);?> ,
        };
        
  
   </script>		


