<?php
	$page -> setTitle("Елена Широва - новости");
?>
<div class='shadow'></div>
	<div class="float_right_arrow">
	  				<div class="arrows_right">
	  				</div>
	  </div>
	  
	   <div class="float_left_arrow">
	   			<div class="arrows_left">
	  			</div>
		</div>
<div class="title_0">
		
		<div class='count_page'></div>		
			
							<div class="preloader"></div>
							<div id="main_portfolio" >					
  	 							<div class="picture_hight_width" >  
  	 		
		<?php
			$sql='SELECT * FROM news ORDER BY date_create DESC';
			$db->query($sql);
			if($db->getCount()>0)
			{
				$arr=$db->getArray();
				foreach($arr as $index=>$val)
				{
					$sql_get_gal='SELECT * FROM news_galery WHERE id_news='.$val['id'].' LIMIT 5';
					$db->query($sql_get_gal);
					if($db->getCount()>0)
					{
						$arr_gal=$db->getArray();
						foreach($arr_gal as $index_gal=>$val_gal)
						{
							$m[]=array($val_gal['photo']);
						}
					}
					else
					{
						$m=array();
					}
					// указываем кодировку
		            mb_internal_encoding("UTF-8");
					$len=200;
		            if (strlen($val['text_rus']) > $len) {
		                $description = mb_substr( $val['text_rus'], 0, $len )."...";
		            }
		            else {
		                $description = $val['text_rus'];
		            }
					$val['date_create']=explode('-',$val['date_create']);
					$val['date_create']=$val['date_create'][2].'.'.$val['date_create'][1].'.'.$val['date_create'][0];
					$mass[]=array('date_create' => $val['date_create'], 'photo' => $val['photo'], 'text_rus' => $description,'id' => $val['id'],'gal'=>$m);
				}
			}
			print '<ul class="digest">';
			for($i=0;$i<3;$i++)
			{
				// указываем кодировку
				    if(!empty($mass[$i]['date_create']))
					{
						mb_internal_encoding("UTF-8");
						$len=200;
			            if (strlen($mass[$i]['text_rus']) > $len) {
			                $description = mb_substr( $mass[$i]['text_rus'], 0, $len )."...";
			            }
			            else {
			                $description = $mass[$i]['text_rus'];
			            }
					print '<li>	<img src="img/news/'.$mass[$i]['photo'].'" alt="thumbinail" class="photo">
							<div class="date">'.$mass[$i]['date_create'].'г</div><p>'.$description.'</p><a href="news/full/id/'.$mass[$i]['id'].'" class="float_left customer_font">читать полностью</a></li>
					';
					}
		            
			}
			print '</ul>';
			
		?>
</div></div></div>
<script type='text/javascript'>
		  var current=3;
		  var page=1;
          var  obj=<?php echo json_encode($mass);?>;

          $('.count_page').replaceWith('<div class="count_page">Страница 1 / '+Math.round((obj.length/3)+ 0.5)+'</div>');
          if(obj.length<=3)
          {
          	$('.float_left_arrow, .float_right_arrow').hide();
          }
          
           $(document).bind('keyup',function(e){
           	       if ($(':animated').length) { return false;}	
           	       else
           	       {
           	       	switch (e.keyCode){
						case 37:
						$('.float_left_arrow').trigger('click');
						break;
						case 39: 
						$('.float_right_arrow').trigger('click');
						break;
					}
           	       }
			})
          $('.float_right_arrow').live('click touchend',function()
          {
          		   if ($(':animated').length) { return false;}	
          		   else
          		   {
          			var next='';
          			var prom_var=current;
          			for(i=page*3;i<page*3+3;i++)
          			{
          				if(i<obj.length)
          				{
          					next+='<li><img src="img/news/'+obj[i]['photo']+'" alt="thumbinail" class="photo"><div class="date">'+obj[i]['date_create']+'г</div><p>'+obj[i]['text_rus']+'</p><a href="news/full/id/'+obj[i]['id']+'" class="float_left customer_font">читать полностью</a></li>';
          					current++;
          				}
          				else
          				{
          					break;
          				}
          			}
          			if(page<Math.round((obj.length/3)+0.5))
          			{
          				page++;	
          			}
          			else
          			{
          				return false;
          			}
          			if(page==Math.round((obj.length/3)+0.5)) { $(this).hide();}
          			if(page>1)
          			{
          				$('.float_left_arrow').show();
          			}
          				
          				if(obj.length-current<=0)
          				{
          					$('.float_right_arrow').addClass('display_none');
          					$('.float_left_arrow').show();
          				}
          			
					$('.count_page').replaceWith('<div class="count_page">Страница '+page+' / '+Math.round((obj.length/3)+0.5)+'</div>');
					
					$('.preloader').show();
  				   	$('.picture_hight_width').animate({marginLeft:'930px'}, 500, function() {
  				   	$('.picture_hight_width').css('margin-left','-930px');
					$('.picture_hight_width').animate({marginLeft:'20px'},500);
					$('.preloader').hide();
					$('.digest').replaceWith('<ul class="digest">'+next+'</ul>'); 
					}) 
          		   }
          			     		
          });
          $('.float_left_arrow').live('click touchend',function()
          {
          	 if ($(':animated').length) { return false;}	
          		   else
          		   {
          		   		if(page==1) { $(this).addClass('display_none'); return false;}
          		 page=page-1;
          		 if(page>1)  $('.float_right_arrow').show();
          			var next='';
          			var prom_var=current;
          			for(i=page*3-3;i<page*3;i++)
          			{
          				if(obj[i]!=false)
          				{
          					next+='<li><img src="img/news/'+obj[i]['photo']+'" alt="thumbinail" class="photo"><div class="date">'+obj[i]['date_create']+'г</div><p>'+obj[i]['text_rus']+'</p><a href="news/full/id/'+obj[i]['id']+'" class="float_left customer_font">читать полностью</a></li>';
          					current--;
          				}
          				else
          				{
          					break;
          				}
          			}
          			if(page==1)
          			{
          				$('.float_left_arrow').hide();
          			}
          				
          			
					$('.count_page').replaceWith('<div class="count_page">Страница '+page+' / '+Math.round((obj.length/3)+0.5)+'</div>');
					$('.preloader').show();
  				   	$('.picture_hight_width').animate({marginLeft:'-930px'}, 500, function() {
  				   	$('.picture_hight_width').css('margin-left','930px');
					$('.picture_hight_width').animate({marginLeft:'20px'},500);
					$('.preloader').hide();
					$('.digest').replaceWith('<ul class="digest">'+next+'</ul>');    
					}) 
          		   }
          		     		
          });
          
   </script>		